# Generated by Django 5.2.7 on 2025-11-06 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_uploadedfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('hi-IN', 'Hindi'), ('en-IN', 'English (India)'), ('ta-IN', 'Tamil'), ('te-IN', 'Telugu'), ('kn-IN', 'Kannada'), ('ml-IN', 'Malayalam'), ('mr-IN', 'Marathi'), ('bn-IN', 'Bengali'), ('gu-IN', 'Gujarati'), ('pa-IN', 'Punjabi')], default='hi-IN', help_text='Language of the audio', max_length=10)),
                ('transcription_text', models.TextField(blank=True, help_text='Transcribed text from audio')),
                ('confidence_score', models.FloatField(blank=True, help_text='Confidence score of transcription (0-1)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of transcription', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if transcription failed')),
                ('audio_metadata', models.JSONField(blank=True, default=dict, help_text='Metadata about the audio file (duration, format, sample_rate, etc.)')),
                ('audio_duration', models.FloatField(blank=True, help_text='Duration of audio in seconds', null=True)),
                ('model_version', models.CharField(default='saarika:v2.5', help_text='SarvamAI model version used', max_length=50)),
                ('sarvam_request_id', models.CharField(blank=True, help_text='SarvamAI request ID for tracking', max_length=100)),
                ('session_id', models.CharField(blank=True, help_text='WebSocket session ID', max_length=100)),
                ('started_at', models.DateTimeField(blank=True, help_text='When processing started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When processing completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who created this transcription', on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transcription',
                'verbose_name_plural': 'Transcriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_transcr_user_id_c1232d_idx'), models.Index(fields=['status'], name='api_transcr_status_767adf_idx'), models.Index(fields=['language_code'], name='api_transcr_languag_c240eb_idx'), models.Index(fields=['session_id'], name='api_transcr_session_54aea8_idx')],
            },
        ),
    ]
